<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TMB_Pedidos.Application\TMB_Pedidos.Application.csproj" />
    <ProjectReference Include="..\TMB_Pedidos.Domain\TMB_Pedidos.Domain.csproj" />
    <ProjectReference Include="..\TMB_Pedidos.Infrastructure\TMB_Pedidos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
